/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ud1_ejer8.gui;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ud1_ejer8.dto.PulsacionesBoton;
import ud1_ejer8.logica.Logica;

/**
 * Ventana principal. Contiene una serie de paneles para mostrar botones, checkboxes
 * y resultados de pulsacion de los mismos.
 * Lo hace usando una estructura de paneles, algunos de ellos con CardLayout
 * para ir mostrando las diferentes partes.
 * 
 * @author Jose Javier BO
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    //ATRIBUTOS
    
    //Referencia a la logica de negocio
    Logica logica;

    /**
     * Creates new form VentantaPrincipal
     * @param logica Referencia a la logica de negocio de la aplicacion. 
     * La usa para ir almacenando
     */
    public VentanaPrincipal(Logica logica) {
        initComponents();
        this.logica = logica;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupMenuInferior = new javax.swing.ButtonGroup();
        panelMenuInferior = new javax.swing.JPanel();
        lbMenuInferior = new javax.swing.JLabel();
        rbAcciones = new javax.swing.JRadioButton();
        rbResultado = new javax.swing.JRadioButton();
        panelCardsMain = new javax.swing.JPanel();
        panelMainInicio = new javax.swing.JPanel();
        lbJuegoPaneles = new javax.swing.JLabel();
        panelMainAciones = new javax.swing.JPanel();
        pmaSuperior = new javax.swing.JPanel();
        lbPmaSuperiorCambiarAcciones = new javax.swing.JLabel();
        inputAcciones = new javax.swing.JComboBox<>();
        pmaPrincipal = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        panelCheckboxes = new javax.swing.JPanel();
        inputLeer = new javax.swing.JCheckBox();
        inputEscalada = new javax.swing.JCheckBox();
        inputEsquiar = new javax.swing.JCheckBox();
        inputSubmarinismo = new javax.swing.JCheckBox();
        panelMainResulatado = new javax.swing.JPanel();
        pmrSuperior = new javax.swing.JPanel();
        lbPmaSuperiorCambiarResultados = new javax.swing.JLabel();
        inputResultados = new javax.swing.JComboBox<>();
        pmrPrincipal = new javax.swing.JPanel();
        panelResultadoBotones = new javax.swing.JPanel();
        lbPanelResultadoBotones = new javax.swing.JLabel();
        prbScroll = new javax.swing.JScrollPane();
        tblResultadoBotones = new javax.swing.JTable();
        panelResultadoSelecciones = new javax.swing.JPanel();
        lbPanelResultadoSelecciones = new javax.swing.JLabel();
        pnlResultadoSelecciones = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenuInferior.setBackground(new java.awt.Color(0, 0, 0));
        panelMenuInferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        lbMenuInferior.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbMenuInferior.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuInferior.setText("CAMBIAR PANELES");
        panelMenuInferior.add(lbMenuInferior);

        btnGroupMenuInferior.add(rbAcciones);
        rbAcciones.setForeground(new java.awt.Color(255, 255, 255));
        rbAcciones.setText("ACCIONES");
        rbAcciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAccionesActionPerformed(evt);
            }
        });
        panelMenuInferior.add(rbAcciones);

        btnGroupMenuInferior.add(rbResultado);
        rbResultado.setForeground(new java.awt.Color(255, 255, 255));
        rbResultado.setText("RESULTADO");
        rbResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbResultadoActionPerformed(evt);
            }
        });
        panelMenuInferior.add(rbResultado);

        getContentPane().add(panelMenuInferior, java.awt.BorderLayout.PAGE_END);

        panelCardsMain.setLayout(new java.awt.CardLayout());

        panelMainInicio.setName("inicio"); // NOI18N

        lbJuegoPaneles.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbJuegoPaneles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbJuegoPaneles.setText("JUEGO DE PANELES");

        javax.swing.GroupLayout panelMainInicioLayout = new javax.swing.GroupLayout(panelMainInicio);
        panelMainInicio.setLayout(panelMainInicioLayout);
        panelMainInicioLayout.setHorizontalGroup(
            panelMainInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbJuegoPaneles, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMainInicioLayout.setVerticalGroup(
            panelMainInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainInicioLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(lbJuegoPaneles)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        panelCardsMain.add(panelMainInicio, "cardInicio");

        panelMainAciones.setName(""); // NOI18N
        panelMainAciones.setLayout(new java.awt.BorderLayout());

        pmaSuperior.setBackground(new java.awt.Color(255, 102, 102));

        lbPmaSuperiorCambiarAcciones.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbPmaSuperiorCambiarAcciones.setText("Cambiar Acciones:");
        pmaSuperior.add(lbPmaSuperiorCambiarAcciones);

        inputAcciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Botones", "Checkboxes" }));
        inputAcciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAccionesActionPerformed(evt);
            }
        });
        pmaSuperior.add(inputAcciones);

        panelMainAciones.add(pmaSuperior, java.awt.BorderLayout.PAGE_START);

        pmaPrincipal.setLayout(new java.awt.CardLayout());

        panelBotones.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 50));

        btn1.setText("B1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        panelBotones.add(btn1);

        btn2.setText("B2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        panelBotones.add(btn2);

        btn3.setText("B3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        panelBotones.add(btn3);

        btn4.setText("B4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        panelBotones.add(btn4);

        pmaPrincipal.add(panelBotones, "cardBotones");

        inputLeer.setText("Leer");

        inputEscalada.setText("Escalada");

        inputEsquiar.setLabel("Esquiar");

        inputSubmarinismo.setLabel("Submarinismo");

        javax.swing.GroupLayout panelCheckboxesLayout = new javax.swing.GroupLayout(panelCheckboxes);
        panelCheckboxes.setLayout(panelCheckboxesLayout);
        panelCheckboxesLayout.setHorizontalGroup(
            panelCheckboxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCheckboxesLayout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addGroup(panelCheckboxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputEsquiar, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(inputLeer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addGroup(panelCheckboxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputSubmarinismo, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(inputEscalada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(100, 100, 100))
        );
        panelCheckboxesLayout.setVerticalGroup(
            panelCheckboxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCheckboxesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelCheckboxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEscalada)
                    .addComponent(inputLeer))
                .addGap(18, 18, 18)
                .addGroup(panelCheckboxesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputEsquiar)
                    .addComponent(inputSubmarinismo))
                .addGap(161, 161, 161))
        );

        pmaPrincipal.add(panelCheckboxes, "cardCheckboxes");

        panelMainAciones.add(pmaPrincipal, java.awt.BorderLayout.CENTER);

        panelCardsMain.add(panelMainAciones, "cardAcciones");

        panelMainResulatado.setName(""); // NOI18N
        panelMainResulatado.setLayout(new java.awt.BorderLayout());

        pmrSuperior.setBackground(new java.awt.Color(0, 204, 0));

        lbPmaSuperiorCambiarResultados.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbPmaSuperiorCambiarResultados.setText("CAMBIAR RESULTADO:");
        pmrSuperior.add(lbPmaSuperiorCambiarResultados);

        inputResultados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pulsaciones", "Selecciones" }));
        inputResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputResultadosActionPerformed(evt);
            }
        });
        pmrSuperior.add(inputResultados);

        panelMainResulatado.add(pmrSuperior, java.awt.BorderLayout.PAGE_START);

        pmrPrincipal.setLayout(new java.awt.CardLayout());

        lbPanelResultadoBotones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbPanelResultadoBotones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPanelResultadoBotones.setText("RECUENTO DE NUMERO DE PULSACION DE BOTONES");

        tblResultadoBotones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "0"},
                {"2", "0"},
                {"3", "0"},
                {"4", "0"}
            },
            new String [] {
                "Boton", "Pulsaciones"
            }
        ));
        tblResultadoBotones.setGridColor(new java.awt.Color(102, 102, 102));
        tblResultadoBotones.setShowGrid(true);
        prbScroll.setViewportView(tblResultadoBotones);

        javax.swing.GroupLayout panelResultadoBotonesLayout = new javax.swing.GroupLayout(panelResultadoBotones);
        panelResultadoBotones.setLayout(panelResultadoBotonesLayout);
        panelResultadoBotonesLayout.setHorizontalGroup(
            panelResultadoBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbPanelResultadoBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelResultadoBotonesLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(prbScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        panelResultadoBotonesLayout.setVerticalGroup(
            panelResultadoBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoBotonesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbPanelResultadoBotones)
                .addGap(29, 29, 29)
                .addComponent(prbScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pmrPrincipal.add(panelResultadoBotones, "card2");

        lbPanelResultadoSelecciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbPanelResultadoSelecciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPanelResultadoSelecciones.setText("OPCIONES SELECCIONADAS");

        pnlResultadoSelecciones.setLayout(new javax.swing.BoxLayout(pnlResultadoSelecciones, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout panelResultadoSeleccionesLayout = new javax.swing.GroupLayout(panelResultadoSelecciones);
        panelResultadoSelecciones.setLayout(panelResultadoSeleccionesLayout);
        panelResultadoSeleccionesLayout.setHorizontalGroup(
            panelResultadoSeleccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResultadoSeleccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPanelResultadoSelecciones, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelResultadoSeleccionesLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(pnlResultadoSelecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelResultadoSeleccionesLayout.setVerticalGroup(
            panelResultadoSeleccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadoSeleccionesLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbPanelResultadoSelecciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlResultadoSelecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pmrPrincipal.add(panelResultadoSelecciones, "card3");

        panelMainResulatado.add(pmrPrincipal, java.awt.BorderLayout.CENTER);

        panelCardsMain.add(panelMainResulatado, "cardResultado");

        getContentPane().add(panelCardsMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Accion menu inferior radio button para mostrar el panel de acciones
     *
     * @param evt
     */
    private void rbAccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAccionesActionPerformed
        //coger re
        CardLayout cl = (CardLayout) panelCardsMain.getLayout();
        cl.show(panelCardsMain, "cardAcciones");
    }//GEN-LAST:event_rbAccionesActionPerformed

    /**
     * Accion menu inferior radio button para mostrar el panel de resultados
     *
     * @param evt
     */
    private void rbResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbResultadoActionPerformed
        
        //actualizar los valores de los resultados
        actualizarResultados();
        
        //mostrar panel de resulados
        CardLayout cl = (CardLayout) panelCardsMain.getLayout();
        cl.show(panelCardsMain, "cardResultado");
    }//GEN-LAST:event_rbResultadoActionPerformed

    /**
     * Selector de que panel de acciones mostrar
     *
     * @param evt
     */
    private void inputAccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAccionesActionPerformed
        
        int seleccion = inputAcciones.getSelectedIndex();
        switch (seleccion) {
            //mostrar el panel de checkboxes
            case 1:
                cambiarPanel(pmaPrincipal, panelCheckboxes);
                break;
            //mostrar el panel de botones
            default:
                cambiarPanel(pmaPrincipal, panelBotones);
        }
    }//GEN-LAST:event_inputAccionesActionPerformed

    /**
     * Selector de que panel de resultados mostrar
     * @param evt 
     */
    private void inputResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputResultadosActionPerformed
        int seleccion = inputResultados.getSelectedIndex();
        switch (seleccion) {
            //mostrar el panel de checkboxes seleccionado
            case 1:
                cambiarPanel(pmrPrincipal, panelResultadoSelecciones);
                break;
            //mostrar el panel tabla de pulsaciones de botones
            default:
                cambiarPanel(pmrPrincipal, panelResultadoBotones);
        }    }//GEN-LAST:event_inputResultadosActionPerformed

    /**
     * Pulsacion en el boton 1
     * @param evt 
     */
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        this.logica.addPulsacion(0);
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * Pulsacion en el boton 2
     * @param evt 
     */

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        this.logica.addPulsacion(1);
    }//GEN-LAST:event_btn2ActionPerformed

    /**
     * Pulsacion en el boton 3
     * @param evt 
     */

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        this.logica.addPulsacion(2);
    }//GEN-LAST:event_btn3ActionPerformed

    /**
     * Pulsacion en el boton 4
     * @param evt 
     */

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        this.logica.addPulsacion(3);
    }//GEN-LAST:event_btn4ActionPerformed

    
    
    
    /**
     * Cambia el panel de un contenedor. Elimina el contenido del contenedor y 
     * muestra un contenido concreto dentro del contenedor. Usa las funciones 
     * repaint() y revalidate() para obligar a refrescarse la gui.
     * <ul>
     * <li>
     * repaint(): Avisa a swing de que debe repintar el componente al completo
     * </li>
     * <li>
     * revalidate(): Avisa al gestor de layout del cambio de componentes lo que lanza
       recalculos de posiciones y tamanos y a su vez el repintado
     * </li>
     * </ul>
     * 
     * @param contenedor Contenedor sobre el que actuar
     * @param contenidoParaMostrar  Contenido que agregar al contenedor
     */
    private void cambiarPanel(JPanel contenedor, JPanel contenidoParaMostrar) {
        
        //eliminar todo el contenido
        contenedor.removeAll();
        
        //agregar el contenido
        contenedor.add(contenidoParaMostrar);
        
        //Avisa al gestor de layout del cambio de componentes lo que lanza
        //recalculos de posiciones y tamanos y a su vez el repintado
        contenedor.revalidate();
        //Avisa a swing de que debe repintar el componente al completo
        contenedor.repaint();
    }

    /**
     * Encargada de actualizar los resultados
     */
    private void actualizarResultados() {
        actualizarSelecciones();
        actualizarPulsaciones();
    }

    /**
     * Actualiza el panel de resultados de seleccionados segun el estado
     * de los checkbox de acciones
     */
    private void actualizarSelecciones() {
        
        //eliminar todos
        pnlResultadoSelecciones.removeAll();
        
        //crear y agregar las etiqueatas segun los checkbox seleccionados
        if (inputEscalada.isSelected()) {
            pnlResultadoSelecciones.add(crearLabel("Escalada"));
        }
        if (inputEsquiar.isSelected()) {
            pnlResultadoSelecciones.add(crearLabel("Esquiar"));
        }
        if (inputLeer.isSelected()) {
            pnlResultadoSelecciones.add(crearLabel("Leer"));
        }
        if (inputSubmarinismo.isSelected()) {
            pnlResultadoSelecciones.add(crearLabel("Submarinismo"));
        }
        
        //Avisa al gestor de layout del cambio de componentes lo que lanza
        //recalculos de posiciones y tamanos y a su vez el repintado
        pnlResultadoSelecciones.revalidate();
        //Avisa a swing de que debe repintar el componente al completo
        pnlResultadoSelecciones.repaint();
    }
    
    /**
     * Crea un JLabel con el texto suministrado y unos parametros de fondo 
     * y tamano determinados
     * @param texto el texto a poner en el JLabel
     * @return El JLabel construido
     */
    private JLabel crearLabel(String texto) {
        JLabel lb = new JLabel(texto);
        lb.setBackground(Color.white);
        lb.setOpaque(true);
        Dimension d = new Dimension(100, 20);
        lb.setMaximumSize(d);
        lb.setPreferredSize(d);
        return lb;
    }
    
    
    /**
     * Actualiza el panel de resultado de pulsaciones
     */
    private void actualizarPulsaciones() {
        //1- Creación del modelo de tabla
        DefaultTableModel dtm =   new DefaultTableModel();
        
        //2- Creo del índice de las columnas en el modelo
        String [] columnas = new String []{"Botón","Pulsaciones"};
        //Establece el nombre a las columnas. Se le debe pasar un object[]
        dtm.setColumnIdentifiers(columnas);
            
        //3- Añado la lista de clientes que tenga en la lógica de negocio
        //Recupero lista clientes
        PulsacionesBoton[] botones = logica.getPulsaciones();
        //La recorro y la voy añadiendo al modelo
        for(PulsacionesBoton boton: botones){
            dtm.addRow(boton.toArrayString());
        }//end foreach
        
        //definir el modelo de la tabla
        tblResultadoBotones.setModel(dtm);
        //hacer que la tabla no sea editable
        tblResultadoBotones.setEnabled(false);
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.ButtonGroup btnGroupMenuInferior;
    private javax.swing.JComboBox<String> inputAcciones;
    private javax.swing.JCheckBox inputEscalada;
    private javax.swing.JCheckBox inputEsquiar;
    private javax.swing.JCheckBox inputLeer;
    private javax.swing.JComboBox<String> inputResultados;
    private javax.swing.JCheckBox inputSubmarinismo;
    private javax.swing.JLabel lbJuegoPaneles;
    private javax.swing.JLabel lbMenuInferior;
    private javax.swing.JLabel lbPanelResultadoBotones;
    private javax.swing.JLabel lbPanelResultadoSelecciones;
    private javax.swing.JLabel lbPmaSuperiorCambiarAcciones;
    private javax.swing.JLabel lbPmaSuperiorCambiarResultados;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelCardsMain;
    private javax.swing.JPanel panelCheckboxes;
    private javax.swing.JPanel panelMainAciones;
    private javax.swing.JPanel panelMainInicio;
    private javax.swing.JPanel panelMainResulatado;
    private javax.swing.JPanel panelMenuInferior;
    private javax.swing.JPanel panelResultadoBotones;
    private javax.swing.JPanel panelResultadoSelecciones;
    private javax.swing.JPanel pmaPrincipal;
    private javax.swing.JPanel pmaSuperior;
    private javax.swing.JPanel pmrPrincipal;
    private javax.swing.JPanel pmrSuperior;
    private javax.swing.JPanel pnlResultadoSelecciones;
    private javax.swing.JScrollPane prbScroll;
    private javax.swing.JRadioButton rbAcciones;
    private javax.swing.JRadioButton rbResultado;
    private javax.swing.JTable tblResultadoBotones;
    // End of variables declaration//GEN-END:variables

}
